channels:
  - conda-forge

dependencies:
  - black
  - flake8
  - ipykernel
  - ipython
  - isort
  - matplotlib
  - nbQA
  - nbstripout
  - numpy
  - pre-commit
  - pycairo
  - python-graphviz
  - python=3.10
  - pyupgrade
  - six
